### PR TITLE
Replace LOGGING_CONFIG BY CATALINA_LOGGING_CONFIG

### PR DESCRIPTION
**Pull request by netbeansuser2019**
To avoid collision e.g. with spring framework like spring-projects/spring-boot#1432

### CODE REVIEW

**Comment by markt-asf** [comment]
In what circumstances is this going to clash with Spring Boot?
My initial reaction to to reject this change as it is going to break existing configurations.

**Comment by ChristopherSchultz** [comment]
Also, `LOGGING_CONFIG` is just an environment variable containing `-Dfoo=bar` arguments to the JVM. Merging `LOGGING_CONFIG` necessary for e.g. Spring with whatever you need for Tomcat should be easy. There should be no need to change anything, here.

**Comment by martin-g** [comment]
> Merging `LOGGING_CONFIG` ... 

merge it how ?

Spring Boot reads this env variable to find the Logback/Log4j2 config file, e.g. `classpath:logback.xml` for Logback. Its value is not as the one Tomcat expects.

**Comment by ChristopherSchultz** [comment]
Spring Boot is only configured via environment variables? Seems fragile and non-portable to me.

**Comment by martin-g** [comment]
Spring Boot could be configured via config file(s), system properties and/or env variables. It is pretty flexible!
Using env variables is the preferred way in Docker/Kubernetes setups.

**Comment by markt-asf** [comment]
Given containers seem to like environment variables, I don't see a way around this. I'm working on a backwards compatible solution.

**Comment by markt-asf** [comment]
Fixed in a backwards compatible manner for all currently supported versions.

**Pull request closed without merging**
