### PR TITLE
 Replace C-style array declaring with Java-style array declaring

### PR DESCRIPTION
**Pull request by lanicc**

### CODE REVIEW

**Comment by martin-g** [comment]
There are many of those. A quick search shows around 400 occurrences of the C-style.
I am not sure this is worth it. It will make backporting very hard.

**Comment by zzk0** [comment]
> There are many of those. A quick search shows around 400 occurrences of the C-style.
> I am not sure this is worth it. It will make backporting very hard.

What if we write new code? Should we write the Java-style array?

**Comment by ChristopherSchultz** [comment]
Yes, please use Java-style array declaration syntax in new code.

**Comment by lanicc** [comment]
I think code style should be unified,especially obvious ones like this

**Comment by martin-g** [comment]
@lanicc We agree that the code style should be consistent and that it should follow Java conventions. But we will do it only when editing such code for other functional changes.

**Pull request closed without merging**
