### PR TITLE
Fix Chinese translation of word "war"

### PR DESCRIPTION
**Pull request by reliveyy**
This PR fixes Chinese translation of word "war". The Chinese word "战争" means the real war not a web archive.

### CODE REVIEW

**Review by bzhaoopenstack — COMMENTED** [review]
Looks good to me. That's the right translation. Thanks.

**Review by martin-g — APPROVED** [review]
A Chinese friend of mine confirmed that this is better!
Thanks, @reliveyy !

**Comment by markt-asf** [comment]
Note to Tomcat committers. If you merge PRs like this you need to be careful because poeditor.com is the master copy for translations. You need to:
- import the latest translations from poeditor
- apply the PR
- export the translations to poeditor (and check it only changes translations affected by the PR)
In some cases it may be easier to manually apply the changes in poeditor and import.

**Comment by markt-asf** [comment]
Thanks. Merged. Please note that our preferred route for translation updates is: https://poeditor.com/projects/view?id=221603

**Pull request merged**
