### PR TITLE
Optimize concurrency

### PR DESCRIPTION
**Pull request by KangZhiDong**
more performance

### CODE REVIEW

**Comment by markt-asf** [comment]
What is the basis for this change?
While the thread is in `wait()`, `notify()` should only be called if one of the conditions in the surrounding `if(...)` is no longer true. I'd expect the change in this PR to make performance marginally worse, not better.

**Comment by KangZhiDong** [comment]
> What is the basis for this change?
> While the thread is in `wait()`, `notify()` should only be called if one of the conditions in the surrounding `if(...)` is no longer true. I'd expect the change in this PR to make performance marginally worse, not better.

When this thread is notify , it do not check "(sendfileRunning && sendfileCount < 1 && addS.size() < 1)" ,but "while" check again,avoid other thread  may change it

**Comment by KangZhiDong** [comment]
> What is the basis for this change?
> While the thread is in `wait()`, `notify()` should only be called if one of the conditions in the surrounding `if(...)` is no longer true. I'd expect the change in this PR to make performance marginally worse, not better.

i think because "while (sendfileRunning && sendfileCount < 1 && addS.size() < 1)"  in outer layer check again,so it  can use "if" there ，do not need check again in synchronized block

**Comment by markt-asf** [comment]
Your analysis is not correct.

**Pull request closed without merging**
