### PR TITLE
search button upgrading

### PR DESCRIPTION
**Pull request by ihsanerben**

### CODE REVIEW

**Comment by ChristopherSchultz** [comment]
Again, why?

**Comment by ihsanerben** [comment]
Hi, I am a Software Engineering student, and we have a project at
university. We need to examine a source code project and then make a pull
request with some improvements. After project deadline, we can delete all
requests.

Christopher Schultz ***@***.***>, 11 Ara 2024 Çar, 18:31
tarihinde şunu yazdı:

**Comment by markt-asf** [comment]
The Tomcat community is not a sandbox for you to use for your university course. This will be reported to GitHub as abusive behaviour.

**Comment by ChristopherSchultz** [comment]
Aw.

Mark, I was actually going to encourage this kind of thing _as long as it's constructive_.

In this particular case, it seems like a change just for the sake of a change.

If someone wants to fix all the typos in the documentation as part of a university course, or to make some minor improvement then I'm all for it.

This PR seems misguided at best but @ihsanerben I would encourage you to try again after taking some more time to identify and make a more meaningful change.

**Pull request closed without merging**
