### PR TITLE
PrepareStatement methods are extracted

### PR DESCRIPTION
**Pull request by DoiMasayuki**
`prepareStatement()` methods are duplicated.
This PR extracts a private method from the `prepareStatement()` methods and simplifies codes.

### CODE REVIEW

**Comment by 72er-de** [comment]
Looks good for me. The same could be done with method prepareCall()?

**Comment by PascalSchumacher** [comment]
If I am not mistaken these classes are a fork of https://github.com/apache/commons-dbcp and are synched from time to time.

Therefore it would be better to create a pull request for https://github.com/apache/commons-dbcp

**Comment by markt-asf** [comment]
Correct. Patches should go to Commons DBCP.

**Comment by DoiMasayuki** [comment]
OK. I requested to Commons DBCP just now. 
Thank you!

**Pull request closed without merging**
