### PR TITLE
API change for Realm and AuthenticatorBase to make remote ip addresses available

### PR DESCRIPTION
**Pull request by spyhunter99**
Related to Bug 59750 https://bz.apache.org/bugzilla/show_bug.cgi?id=59750

Goal: for the LockedRealm, be able to log where the failed login attempt came from

### CODE REVIEW

**Comment by michael-o** [comment]
Oh hell, this  will break the public API in a patch release. Especially for custom components. They won't retrain backward compat. Isn't there a better way for this?

**Comment by spyhunter99** [comment]
next best option is to add a new method signature which will also impact the public api. It's slightly less impactful for users that have extended any of the base classes but if they have implemented the interface, they will still have to add the new method.

**Comment by michael-o** [comment]
I'd really like to go with listeners as proposed just like the Spring Secutiry framework does. You will be able to do whatever your want with that information.

**Comment by spyhunter99** [comment]
OK. i'll see if i can get to work on that

**Comment by michael-o** [comment]
Please have a look what @ChristopherSchultz has proposed on the ticket.

**Pull request closed without merging**
