### PR TITLE
Doc correction

### PR DESCRIPTION
**Pull request by marcorobiati**

### CODE REVIEW

**Review by aooohan — APPROVED** [review]
LGTM.

**Comment by aooohan** [comment]
Thanks for the PR. ;)

**Comment by marcorobiati** [comment]
What LGTM means? And is this doc the same that goes on the website or just a copy integrated in the release? In case where to contribute to the online doc?

**Comment by aooohan** [comment]
> What LGTM means? 

That means 'Looks Good To Me'.

> And is this doc the same that goes on the website or just a copy integrated in the release? In case where to contribute to the online doc?

Yes, this doc same with the website and the doc goes on the website will update after next release.

**Pull request merged**
