### PR TITLE
Document conditions under which the AprLifecycleListener can be used …

### PR DESCRIPTION
**Pull request by michael-o**
…to avoid JVM crashes

This basically document cases to avoid issues like
https://github.com/spring-projects/spring-boot/issues/28472

### CODE REVIEW

**Comment by michael-o** [comment]
> 
> 
> > [...] so the second Tomcat now shuts down APR globally, releasing the global structures. The first Tomcat is now shutting down, its `AprConnector` tries to use a sub APR pool/object from a pool which has already been released.
> 
> There is no `AprConnector`. 
I actually meant the connector using the APR Protocol with the APR endpoint.

Where is the Java call which eventually goes down into native to cause this problem? As the AprLifecycleListener is stopping, it should not try to use any APR pool. Perhaps the other connector is still trying to actually use pool objects in some other way. If that's the case, the problem isn't with double-shutdown. It's with shutdown-while-trying-to-still-do-stuff.
> 
> So can we get a Java stack trace for where this is crashing? It should be simple to check to see if APR has been killed at some point and at least not crash the JVM.

How does this actually matter?  If APR has been globally terminated any subsequent operation to any APR object is deemed to fail and that this what happens here. The problem is just init and destroy and wrong points in time. That's it.

```
Stack: [0x00007fffdcccc000,0x00007fffdcdcc000],  sp=0x00007fffdcdcae70,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libapr-1.so.0+0x336fa]  signed char+0x1a
C  [libtcnative-1.so.0.2.24+0x19a06]  Java_org_apache_tomcat_jni_Address_get+0x36
j  org.apache.tomcat.jni.Address.get(IJ)J+0
j  org.apache.tomcat.util.net.AprEndpoint.getLocalAddress()Ljava/net/InetSocketAddress;+15
j  org.apache.tomcat.util.net.AbstractEndpoint.unlockAccept()V+26
j  org.apache.tomcat.util.net.AbstractEndpoint.closeServerSocketGraceful()V+23
j  org.apache.coyote.AbstractProtocol.closeServerSocketGraceful()V+4
j  org.apache.catalina.core.StandardService.stopInternal()V+35
j  org.apache.catalina.util.LifecycleBase.stop()V+214
j  org.apache.catalina.core.StandardServer.stopInternal()V+82
j  org.apache.catalina.util.LifecycleBase.stop()V+214
j  org.apache.catalina.startup.Tomcat.stop()V+9
j  org.springframework.boot.web.embedded.tomcat.TomcatWebServer.stopTomcat()V+29
j  org.springframework.boot.web.embedded.tomcat.TomcatWebServer.stop()V+32
j  org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.stop()V+4
j  org.springframework.context.SmartLifecycle.stop(Ljava/lang/Runnable;)V+1
```

This is from the main Tomcat instance and shutdown time. The management one is already gone.

**Comment by michael-o** [comment]
@ChristopherSchultz Here is an extremely primitive test case:
```java
public class TomcatEmbeddedTest {

	static class ShutdownHook2 extends Thread {
		Tomcat tomcat;
		Tomcat tomcat2;

		public void run() {
			try {
				Thread.sleep(5000L);
			} catch (InterruptedException e1) {
				e1.printStackTrace();
			}

			try {
				tomcat2.stop();
				tomcat2.destroy();
				tomcat.stop();
				tomcat.destroy();

			} catch (LifecycleException e) {
				e.printStackTrace();
			}
		}
	}

	public static void main(String[] args) throws LifecycleException {
		Tomcat tomcat = new Tomcat();
		tomcat.setPort(18888);
		AprLifecycleListener listener = new AprLifecycleListener();
		listener.setUseAprConnector(true);
		listener.setUseOpenSSL(true);
		tomcat.getServer().addLifecycleListener(listener);
		tomcat.getConnector();
		tomcat.init();

		Tomcat tomcat2 = new Tomcat();
		tomcat2.setPort(28888);
		AprLifecycleListener listener2 = new AprLifecycleListener();
		listener2.setUseAprConnector(true);
		listener2.setUseOpenSSL(true);
		tomcat2.getServer().addLifecycleListener(listener2);
		tomcat2.getConnector();
		tomcat2.init();

		ShutdownHook2 sh2 = new ShutdownHook2();
		sh2.tomcat = tomcat;
		sh2.tomcat2 = tomcat2;

		sh2.start();

		tomcat.start();
		tomcat2.start();
	}

}
```

Output:
```
Okt 29, 2021 8:26:01 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFORMATION: Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
Okt 29, 2021 8:26:01 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFORMATION: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
Okt 29, 2021 8:26:01 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFORMATION: APR/OpenSSL configuration: useAprConnector [true], useOpenSSL [true]
Okt 29, 2021 8:26:01 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
INFORMATION: OpenSSL successfully initialized [OpenSSL 1.1.1l  24 Aug 2021]
Okt 29, 2021 8:26:01 PM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-apr-18888"]
Okt 29, 2021 8:26:01 PM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-apr-28888"]
Okt 29, 2021 8:26:01 PM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service [Tomcat]
Okt 29, 2021 8:26:01 PM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-apr-18888"]
Okt 29, 2021 8:26:01 PM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service [Tomcat]
Okt 29, 2021 8:26:01 PM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-apr-28888"]
Okt 29, 2021 8:26:06 PM org.apache.coyote.AbstractProtocol pause
INFORMATION: Pausing ProtocolHandler ["http-apr-28888"]
Okt 29, 2021 8:26:06 PM org.apache.catalina.core.StandardService stopInternal
INFORMATION: Stopping service [Tomcat]
Okt 29, 2021 8:26:06 PM org.apache.coyote.AbstractProtocol stop
INFORMATION: Stopping ProtocolHandler ["http-apr-28888"]
Okt 29, 2021 8:26:06 PM org.apache.coyote.AbstractProtocol destroy
INFORMATION: Destroying ProtocolHandler ["http-apr-28888"]
Okt 29, 2021 8:26:06 PM org.apache.coyote.AbstractProtocol pause
INFORMATION: Pausing ProtocolHandler ["http-apr-18888"]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000001800011dd, pid=19692, tid=0x0000000000004138
#
# JRE version: OpenJDK Runtime Environment (Zulu 8.52.0.24-SA-win64) (8.0_282-b08) (build 1.8.0_282-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.282-b08 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# Okt 29, 2021 8:26:06 PM org.apache.tomcat.util.net.Acceptor run
SCHWERWIEGEND: Socket accept failed
org.apache.tomcat.jni.Error: 730004: Ein Blockierungsvorgang wurde durch einen Aufruf von WSACancelBlockingCall unterbrochen.
        at org.apache.tomcat.jni.Socket.accept(Native Method)
        at org.apache.tomcat.util.net.AprEndpoint.serverSocketAccept(AprEndpoint.java:753)
        at org.apache.tomcat.util.net.AprEndpoint.serverSocketAccept(AprEndpoint.java:85)
        at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:106)
        at java.lang.Thread.run(Thread.java:748)

C  [tcnative-1.dll+0x11dd]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Entwicklung\workspace-2020-12\tomcat-embedded-tester\hs_err_pid19692.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by ChristopherSchultz** [comment]
Your test-case looks even more complicated than necessary: just initialize two of them then deinitialize them. No shutdown hook necessary, right?

Okay, so it's not crashing in the `AprLifecycleListener`'s shutdown, which is what it sounded like you were reporting.

Certainly, anything can crash at any time after the APR global pools have been shut-down. We could put guards around those things. Something like this at the top of each of the calls which require APR:

```
#DEFINE CHECK_APR_INITIALIZED(ENV) { \
  if(!tcn_global_pool) { \
    tcn_ThrowAPRException((ENV), APR_EINIT); \
  } \
} \

TCN_IMPLEMENT_CALL(jstring, Address, getnameinfo)(TCN_STDARGS,
                                                  jlong sa, jint flags)
{
    apr_sockaddr_t *s = J2P(sa, apr_sockaddr_t *);
    char *hostname;

    UNREFERENCED(o);
  CHECK_APR_INITIALIZED(e); /* <- This macro invocation is new */
    if (apr_getnameinfo(&hostname, s, (apr_int32_t)flags) == APR_SUCCESS)
        return AJP_TO_JSTRING(hostname);
    else
        return NULL;
}
```

It would be much cleaner to implement this at the Java level, but as your test-case demonstrates, it's always possible for APR to disappear during the execution of one of the native methods.

I'm kind of curious as to exactly where in `Socket.accept()` this particular failure occurred. We use APR pools for things like string values, even to throw exceptions. So it's hard to avoid using APR anywhere. One could argue that APR pools aren't necessary for throwing exceptions, but re-writing tcnative at this point to remove APR-type things is unlikely. Perhaps incrementally. But Rémy's recent work with Project Panama looks like we might be able to dump tcnative in the reasonably-near future.

Anyway, back to fixing this kind of thing:

1. I think it's worth mentioning the dangers of multiple AprLifecycleListeners in the Tomcat documentation. I don't think the PR as submitted goes far enough. I think it's even misleading at first (e.g. only use `AprLifecycleListener` on a `Server` element) because there are many ways to use the `AprLifecycleListener` in ways that can cause the JVM to crash. I think this documentation should be changed in the Javadoc but also in the documentation for the listener in general, here http://tomcat.apache.org/tomcat-10.0-doc/apr.html#APR_Lifecycle_Listener_Configuration and here http://tomcat.apache.org/tomcat-10.0-doc/config/listeners.html#APR_Lifecycle_Listener_-_org.apache.catalina.core.AprLifecycleListener. (Note that the second of these two already states that the listener should only be used on `<Server>` components.)
1. I think it's also reasonable to try to protect the JVM against this kind of failure. Anyone starting two Tomcats in a single JVM is going to have exactly the same problem. Yes, it's possible to have the "container" (e.g. Spring in this case) manage the whole, um, _lifecycle_ of the `AprLifecycleListener` but it's much more natural to use it "inside" Tomcat and allow Tomcat to manage that process.

I like the idea of reference-counting, especially because the number of times the `AprLifecycleListener` is initialized and de-initialized in a given JVM should be relatively low. It's a small amount of code to manage, provides a great amount of protection (JVM crashes should really never be tolerated), and the performance impact is irrelevant.

Would you care to prepare a reference-counting patch for `AprLifecycleListener` either as a part of this PR, or as a separate one?

**Comment by michael-o** [comment]
> Your test-case looks even more complicated than necessary: just initialize two of them then deinitialize them. No shutdown hook necessary, right?

This maybe true, but it replicates the behavior in Spring Boot. This is what I wanted to show you.
 
> Okay, so it's not crashing in the `AprLifecycleListener`'s shutdown, which is what it sounded like you were reporting.

I don't think I have actually written that. It is the APR protocol/endpoint.

> Certainly, anything can crash at any time after the APR global pools have been shut-down. We could put guards around those things. Something like this at the top of each of the calls which require APR:
> 
> ```
> #DEFINE CHECK_APR_INITIALIZED(ENV) { \
>   if(!tcn_global_pool) { \
>     tcn_ThrowAPRException((ENV), APR_EINIT); \
>   } \
> } \
> 
> TCN_IMPLEMENT_CALL(jstring, Address, getnameinfo)(TCN_STDARGS,
>                                                   jlong sa, jint flags)
> {
>     apr_sockaddr_t *s = J2P(sa, apr_sockaddr_t *);
>     char *hostname;
> 
>     UNREFERENCED(o);
>   CHECK_APR_INITIALIZED(e); /* <- This macro invocation is new */
>     if (apr_getnameinfo(&hostname, s, (apr_int32_t)flags) == APR_SUCCESS)
>         return AJP_TO_JSTRING(hostname);
>     else
>         return NULL;
> }
> ```

This sounds like a decent idea. It makes post mortem analysis much easier. It is work, but just manual one.

> It would be much cleaner to implement this at the Java level, but as your test-case demonstrates, it's always possible for APR to disappear during the execution of one of the native methods.

Agreed.

> I'm kind of curious as to exactly where in `Socket.accept()` this particular failure occurred. We use APR pools for things like string values, even to throw exceptions. So it's hard to avoid using APR anywhere. One could argue that APR pools aren't necessary for throwing exceptions, but re-writing tcnative at this point to remove APR-type things is unlikely. Perhaps incrementally. But Rémy's recent work with Project Panama looks like we might be able to dump tcnative in the reasonably-near future.

Unlikely since Tomat 9 and 10 will live very long and the minimum Java version is 8. Expect tomcat-native as of now to live for at least five more years. A future version with Panama will likely to have OpenSSL only, for now.

> Anyway, back to fixing this kind of thing:
> 
>     1. I think it's worth mentioning the dangers of multiple AprLifecycleListeners in the Tomcat documentation. I don't think the PR as submitted goes far enough. I think it's even misleading at first (e.g. only use `AprLifecycleListener` on a `Server` element) because there are many ways to use the `AprLifecycleListener` in ways that can cause the JVM to crash. I think this documentation should be changed in the Javadoc but also in the documentation for the listener in general, here http://tomcat.apache.org/tomcat-10.0-doc/apr.html#APR_Lifecycle_Listener_Configuration and here http://tomcat.apache.org/tomcat-10.0-doc/config/listeners.html#APR_Lifecycle_Listener_-_org.apache.catalina.core.AprLifecycleListener. (Note that the second of these two already states that the listener should only be used on `<Server>` components.)

This is the first problem, the documentation you mention is intended for integrators and admins. Embedders read Javadoc only, as you have seen with Spring Boot. Wen should add at least minimal information to all of these listeners' Javadoc and maybe a link to the extended documentation. (our fault)

What would be your proposal for the documentation.

>     2. I think it's also reasonable to try to protect the JVM against this kind of failure. Anyone starting two Tomcats in a single JVM is going to have exactly the same problem. Yes, it's possible to have the "container" (e.g. Spring in this case) manage the whole, um, _lifecycle_ of the `AprLifecycleListener` but it's much more natural to use it "inside" Tomcat and allow Tomcat to manage that process.

Yes, natural as long as you adibe and know the contract and requirements which partially did not happen in Spring Boot. I am inclined to add a WARNING log to all of these listeners when the `Lifecycle` is not of instance `Server`.

> I like the idea of reference-counting, especially because the number of times the `AprLifecycleListener` is initialized and de-initialized in a given JVM should be relatively low. It's a small amount of code to manage, provides a great amount of protection (JVM crashes should really never be tolerated), and the performance impact is irrelevant.
> 
> Would you care to prepare a reference-counting patch for `AprLifecycleListener` either as a part of this PR, or as a separate one?

I would like to take care of the documentation shortage first and then discuss in a separate PR/thread reference counting approach.

**Comment by michael-o** [comment]
@ChristopherSchultz I have just generally copied the sentence (verbatim) from the website docs to listeners Javadoc.

**Comment by markt-asf** [comment]
Merged manually

**Pull request closed without merging**
