### PR TITLE
Sort the resource list,Ensure consistency in the order of loading res…

### PR DESCRIPTION
**Pull request by zxm1234**
…ources.

### CODE REVIEW

**Comment by markt-asf** [comment]
Closing see https://bz.apache.org/bugzilla/show_bug.cgi?id=57129 for the reasons.

**Comment by songxiaosheng** [comment]
> https://bz.apache.org/bugzilla/show_bug.cgi?id=57129

From the user's perspective, there is a greater risk in the uncertainty of not sorting. Previous discussions did not seem to pay much attention to this issue. After long-term research, it was found that SpringBoot has sorted the class loading order. The website From the user's perspective, this Tomcat sorting is necessary. If you just look at it from the perspective of historical habits and developers, it doesn't feel good.

**Comment by ChristopherSchultz** [comment]
Anyone who wants this should lobby the Jakarta Servlet Experts Group. It's the only way this is likely to get into Tomcat.

**Comment by songxiaosheng** [comment]
> Anyone who wants this should lobby the Jakarta Servlet Experts Group. It's the only way this is likely to get into Tomcat.

Thank you. I feel it's worth a try

**Pull request closed without merging**
