### PR TITLE
Update BUILDING and CONTRIBUTING docs after the svn->git migration.

### PR DESCRIPTION
**Pull request by csutherl**
I'm opening this PR for some review/help. There are a couple of references to SVN left in the documentation (MERGE.txt and BUILDING.txt) that I'm not sure how to adjust. Anyone have thoughts on that?

### CODE REVIEW

**Comment by csutherl** [comment]
The [svn:eol-style](https://github.com/apache/tomcat/blob/master/BUILDING.txt#L549) is what I'm unsure of in BUILDING.txt. I don't see an obvious equivalent in git, but didn't want to trash the note because it's important.

For MERGE.txt, should that be left alone? It looks like that's a more generic file than something specific to Tomcat.

**Comment by funkman** [comment]
Agreed, I tried looking at the dev archives for opinions of git EOL ending settings (core.autocrlf) and didn't see anything. I'd be tempted to add something to the FAQ with respect to this.  (Assuming there is consensus on what those settings might be)

**Comment by markt-asf** [comment]
It gets a mention at the end of https://wiki.apache.org/general/GitAtApache

Probably worth a dev@ discussion

**Comment by markt-asf** [comment]
Test ping.

**Comment by csutherl** [comment]
Do we want to accept this commit so that the docs mostly reflect our current state and fire off a discussion re: `svn:eol-style`?

**Comment by markt-asf** [comment]
+1

**Comment by csutherl** [comment]
I've accepted the PR and will follow up on the dev@ list with a discussion on an `svn:eol-style` equivalent.

**Pull request merged**
