### PR TITLE
Introduce Tomcat Source-to-Image (S2I)

### PR DESCRIPTION
**Pull request by maxime-beck**
# Tomcat - Source-to-Image (S2I)
This resource provides a CentOS-based Docker image that enables [Source-to-Image](https://github.com/openshift/source-to-image) building for Tomcat. It builds the sources of a webapp and deploys it to a fully functional containerized Tomcat Server. The generated image can then easily be run locally or deployed to a Kubernetes-based Server.

## Usage
1. Build an image:
```bash
$ s2i build [SOURCE_URL] tomcat-s2i my-webapp-image
```
Where `[SOURCE_URL]` is either the URL to a Git repository or a path to local sources.

2. Run it:
```bash
$ docker run -p 8080:8080 my-webapp-image
```

### CODE REVIEW

**Comment by michael-o** [comment]
I am against pulling this one for several reasons:

* This is CentOS-specific and OpenShift
* Someone has to maintain it, likely none of us won't
* It duplicates several configuration files

This is best handled by the community or by Red Hat ($$$)

**Comment by jfclere** [comment]
Actually using Alpine like in res/tomcat-maven/Dockerfile might be a good idea.
The tool to build the image is independent of Openshift and the image will run in Kubernetes too.

**Comment by maxime-beck** [comment]
Yes, switching to Alpine is definitely possible. I can update the PR if needed.

**Comment by ChristopherSchultz** [comment]
I'm not sure this is something appropriate for the Tomcat team to adopt. Sounds like a great community-led project to exist outside of Tomcat, though.

**Comment by markt-asf** [comment]
Agree this doesn't belong in the Tomcat source tree.

**Pull request closed without merging**
