### PR TITLE
Create Documentation  installing tomcat on ibm cloud

### PR DESCRIPTION
**Pull request by Sumithkr**
Add this document on documentation page 
[Tomcat.docx](https://github.com/apache/tomcat/files/5612520/Tomcat.docx)

### CODE REVIEW

**Comment by martin-g** [comment]
IMO this document should be part of IBM Cloud documentation. We cannot maintain it.

**Comment by Sumithkr** [comment]
it has instructions that how to install tomcat on ibm cloud

**Comment by martin-g** [comment]
Tomcat cannot maintain documentation for all the cloud providers out there. It is their responsibility to explain what they did differently than the official Tomcat documentation.

**Comment by rmaucher** [comment]
The wiki can still be a good spot for this kind of thing, as long as it is organized properly and maintained.

**Comment by Sumithkr** [comment]
https://mariadb.com/kb/en/installing-mariadb-on-ibm-cloud/
check this same documentation is for tomcat

**Pull request closed without merging**
