### PR TITLE
Enabled headless build configuration

### PR DESCRIPTION
**Pull request by tbw777**

### CODE REVIEW

**Comment by markt-asf** [comment]
What problem is this PR trying to solve?

**Comment by tbw777** [comment]
no problem, just selecting less jvm api to work

**Comment by ChristopherSchultz** [comment]
If no code requests anything AWT-related, then the headless config of the JVM makes no difference. I see no improvement here at all, just added lines to an already complex build script.

**Comment by tbw777** [comment]
Also this is guarantee that no awt components used

**Comment by ChristopherSchultz** [comment]
It does not guarantee that no AWT components are used. It only guarantees that anything which requires an actual screen will fail (such as trying to open a Frame, etc.). AWT is still perfectly usable when "headless". In fact, that's the whole point of putting the JVM into "headless" mode: to allow AWT to be used even when there isn't a "head" (screen).

**Comment by markt-asf** [comment]
I don't see any benefit to adding these extra settings.

**Pull request closed without merging**
