### PR TITLE
BZ 66513: Enforce one concurrent request per session requirement

### PR DESCRIPTION
**Pull request by markt-asf**
This is untested.

If accepted, this will need some documentation updates.

The purpose of this draft is to obtain early feedback on the approach.

### CODE REVIEW

**Comment by rmaucher** [comment]
That seems like the better way to do it.

**Comment by rmannibucau** [comment]
* Is there a plan for the map eviction? background thread?
* How does it work in a cluster since counter is local, should it be a cluster event?

**Comment by markt-asf** [comment]
Map eviction is handled in the finally block.

That we can only make this work on a single node is why Rémy is proposing that we remove/deprecate this Valve.

**Review by aooohan — APPROVED** [review]
LGTM.

**Comment by markt-asf** [comment]
I haven't deprecated this yet. I'm waiting on input from the OP of BZ 66513 and/or @jfclere as the original author of the Valve in case there is a use case I have missed.

**Comment by rmaucher** [comment]
Very clean overall, esp the javadoc update.

**Comment by jfclere** [comment]
@markt-asf that looks better that what was there ;-)

**Comment by markt-asf** [comment]
> @markt-asf that looks better that what was there ;-)

Thanks.

Can you recall if there was a use case for this Valve on a single node? Or was it always intended for use behind a non-sticky load-balancer and, therefore, it was up to the client to enforce the "no more than one concurrent request per session" rule?

**Comment by jfclere** [comment]
trying to remember...  I guess I wrote to save and restore session information for a SINGLE tomcat node.

**Pull request merged**
