### PR TITLE
Apply the suggestion in rfc7233

### PR DESCRIPTION
**Pull request by zhanhb**

### CODE REVIEW

**Comment by markt-asf** [comment]
Thanks. I have applied 2 of the 3 changes to 9.0.x (range units and etag) with some additional refactoring / clean-up as well as additional comments.
I thin the remaining change needs to be made optional as many clients have implemented partial PUT even if the intention of the RFC 2616 authors was not to allow it. This is next on my TODO list followed by back-porting all the Rnage improvements inspired by your PRs.

**Comment by zhanhb** [comment]
For a put request, usually it won't have a header 'Range', The header specified in rfc 2616 is 'Content-Range'.
What will happen to a put request if header 'Range' is specified?
Put the content in specified URI and then return partial content of the entity. We can see existed source in tomcat, either 201 or 204 is returned, both have no response body content.
IMO, this change can also be applied too.

**Comment by markt-asf** [comment]
Thanks for the the review. I had mis-remembered how partial PUTs were implemented. I'll take another pass at the patch.

**Comment by markt-asf** [comment]
I think everything is complete now. Feel free to re-open if you spot something I missed.

**Comment by zhanhb** [comment]
Good job, there is no issue with the range request now.

**Pull request closed without merging**
