### PR TITLE
service.bat handles changed Service at installation

### PR DESCRIPTION
**Pull request by bkiselka**
Enable service.bat to deal with changed "Windows Service Name" defined during Tomcat Windows Installation.

During the Apache Tomcat Setup You can define on the "Configuration Options" page a "Windows Service Name". If you change the default "Tomcat8" this results not only in a changed installation folder and a changed Windows Service Name, but also to renamed files bin/Tomcat8.exe and bin/Tomcat8w.exe.

The proposed changes deal with renamed Windows service wrapper executables by using the provided parameter name for the service name. Note that the parameter is no longer optional then!

Another solution would be to change the Windows installer and do not rename the bin/Tomcat@VERSION_MAJOR@.exe and                     bin/Tomcat@VERSION_MAJOR@w.exe during installation.

### CODE REVIEW

**Comment by bkiselka** [comment]
Could You please state, why you closed the Pull Request?

The Tomcat Windows Installer renames the files bin/Tomcat8.exe and bin/Tomcat8w.exe, which cannot be found by the bin/service.bat afterwards.
To me this is a bug!

Both the installer https://github.com/apache/tomcat/commits/master/res/tomcat.nsi and the https://github.com/apache/tomcat/blob/master/bin/service.bat did not change.

Or shall I open a bug on https://bz.apache.org/bugzilla first?

**Comment by markt-asf** [comment]
Re-open PR that was closed as a side effect of the svn -> git migration.

**Comment by markt-asf** [comment]
For reference, this was the trigger for the filename to change:
https://bz.apache.org/bugzilla/show_bug.cgi?id=50949

The advantage of changing the file name is that Commons Daemon derives the current service name from it so it doesn't have to be explicitly specified.

**Comment by markt-asf** [comment]
The patch needs some more work. Currently it works if you install a different service name using the installer (because `tomcat9[w].exe` are renamed) but it fails if you install from the zip and try `service.bat install foo`
I suggest you update the patch to first look for `tomcat9[w].exe` and then, if that is not found, `servicename[w].exe`

**Comment by markt-asf** [comment]
I started to implement the above suggestion and hit another issue. If you install via the installer with a non-standard name you can;t rename the service because the .exe files have been renamed.

Having looked at various options I think the best option is as follows:
- leave the installer as is
- require the service name to be provided unless the default name is used
- rename .exe files when installing non-default service name from batch file (to align with installer behaviour)
- rename .exe files to defaults when uninstalling non-default service name from batch file (to allow subsequent installations to use any valid service name)

These last two points are the main change. Unless there are objections, I'll proceed on this basis later this week.

**Comment by bkiselka** [comment]
Sorry that I had no time to tackle your proposed changes from 9 Apr for the installation from zip file via batch file.
All your proposed changes from 30 July sound reasonable and clear to me (no objections!) and are necessary to solve the issue.

**Comment by markt-asf** [comment]
Closing at this has been implemented but with a modified approach that handled the renaming of the executables.

**Pull request closed without merging**
