### PR TITLE
lazy set filed `DELETE_FILES_SERVICE` 

### PR DESCRIPTION
**Pull request by dao-jun**
Lazy set field `DELETE_FILES_SERVICE` to avoid class `ThreadPoolExecutor` loaded earlier than tomcat start.

Actually, some `APM` systems enhance class `ThreadPoolExecutor` with `java agent`,  the field `DELETE_FILES_SERVICE` may cause enhance failed.

### CODE REVIEW

**Comment by martin-g** [comment]
Please provide more information what kind of issue you have now!
The description is a bit vague at the moment.

**Comment by dao-jun** [comment]
> Please provide more information what kind of issue you have now!
> The description is a bit vague at the moment.

  We use `java agent` to enhance class `ThreadPoolExecutor` to provide `cross thread trace monitor ability`, but we found that class `ThreadPoolExecutor`  loaded before agent start, it caused by class `AsyncFileHandler` which defined in `logging.properties`.  So that `java agent` could not enhance class `ThreadPoolExecutor`.  Event we replaced `org.apache.juli.AsyncFileHandler` with `java.util.logging.FileHandler`  to avoid the issue, but I want to fix it.

**Comment by markt-asf** [comment]
How does this fix the issue? It only delays the creation of the executor from the point the class is loaded to the point where the first instance is created. Instance creation is also triggered by the parsing of logging.properties and occurs immediately the class is loaded. The class loading is triggered by the instance creation so I don't see how this proposed PR can help.

**Comment by dao-jun** [comment]
> How does this fix the issue? It only delays the creation of the executor from the point the class is loaded to the point where the first instance is created. Instance creation is also triggered by the parsing of logging.properties and occurs immediately the class is loaded. The class loading is triggered by the instance creation so I don't see how this proposed PR can help.

Yes, I just noticed it create an instance in `ClassLoaderLogManager#readConfiguration` by invoking `classLoader.loadClass(handlerClassName).getConstructor().newInstance()`, I'm sorry for that.     How about using a single `Thread` instead of `ThreadPoolExecutor` ?

**Comment by markt-asf** [comment]
Switching a single thread would just require the re-implementation of a chunk of the Executor functionality.
One option would be to move lazy init to clean() and then configure maxDays=0 if you want to use your agent.

**Pull request closed without merging**
