### PR TITLE
webdav lock and unlock: ensure response must not be cached

### PR DESCRIPTION
**Pull request by Chenjp**
Make sure that Responses of lock / unlock methods MUST NOT be cached, per rfc4918. 
see #disableCacheable()
testcase added.

### CODE REVIEW

**Comment by rmaucher** [comment]
All of the WebDAV methods are "must not cache" actually (except PROPFIND, but IMO it's a bad idea to cache it), and it is 100% obvious why. If the proxy feels like it doesn't have to send the MKCOL to Tomcat, things are not going to work. I don't know if the WebDAV Servlet should have built in headers for that or the users should use a valve, filter or something instead (like the obvious: DO NOT use a caching proxy on the WebDAV location !).

Personally I am "done" with the WebDAV Servlet. The area had no tests (Litmus was sometimes run manually by Mark it seems) so according to our previous meetings there was a need to improve that. Along the way I found design problems and bugs I had to fix, and it now seems good enough (Litmus passes and the testcase scenarios are rather complex). I don't believe there are lots of users for this, so as far as I am concerned it is more than enough.

When adding tests, you might want to look at that: https://nightlies.apache.org/tomcat/tomcat-12.0.x/coverage/org.apache.catalina.servlets/index.html#dn-a
You can set test.coverage=true (and also add execute.validate=true) in your build.properties to see if new tests improve that or if things were already covered.

**Comment by markt-asf** [comment]
This change is unnecessary. As per RFC 9111, methods other than GET are only cached if the method definition allows it. RFC 4918 is explicit that these methods are not cacheable.

**Comment by rmaucher** [comment]
OTOH, +1 if you want to rewrite (they are too verbose right now) and expand the WebDAV tests.

**Comment by Chenjp** [comment]
> This change is unnecessary. As per RFC 9111, methods other than GET are only cached if the method definition allows it. RFC 4918 is explicit that these methods are not cacheable.

Currently, expiresFilter with default conf will enable cache for those LOCK/UNLOCK etc. If source server do not explicitly disable it, then other component like ExpiresFilter, Nginx/Apache Httpd, F5, Proxy Server will have to be responsible for that. 
If the proxy server of our user, how to resolve it - Ask their IT team to modify proxy setting?

**Comment by markt-asf** [comment]
If the `ExpiresFilter` is setting cache control headers when it should then that Filter should be fixed. The same goes for any other component setting cache headers incorrectly.

**Comment by Chenjp** [comment]
> If the `ExpiresFilter` is setting cache control headers when it shouldn't then that Filter should be fixed. The same goes for any other component setting cache headers incorrectly.



> OTOH, +1 if you want to rewrite (they are too verbose right now) and expand the WebDAV tests.

I started reading rfc4918 three weeks ago, and yesterday when i submitted the code i found that @rmaucher you had almost finished WebDAV rfc support.

**Comment by Chenjp** [comment]
@markt-asf @rmaucher please advise following issue need fix or not? -- If necessary, I will submit PR.
```java
java.lang.AssertionError: 9.10.2. Refreshing Locks - Values other than 0 or infinity MUST NOT be used with the Depth header on a LOCK method. Depth header `1` is invalid. expected:<400> but was:<200>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.apache.catalina.servlets.TestWebdavServletRfcSection_9_10.testRfc_9_10_2(TestWebdavServletRfcSection_9_10.java:199)

java.lang.AssertionError: 9.10.3. Depth and Locking - The Depth header may be used with the LOCK method. Depth header `-1` is invalid. 4xx status coude expected, actual status code was 200
	at org.apache.catalina.servlets.WebdavServletRfcSectionBase$WebdavClient.lockResource(WebdavServletRfcSectionBase.java:164)
	at org.apache.catalina.servlets.TestWebdavServletRfcSection_9_10.testRfc_9_10_3(TestWebdavServletRfcSection_9_10.java:280)	

java.lang.AssertionError: 9.11. UNLOCK Method - 400 (Bad Request) expected due to `No lock token was provided`., Failed to unlock(lockToken=null), actual status code was 409
	at org.apache.catalina.servlets.WebdavServletRfcSectionBase$WebdavClient.unlockResource(WebdavServletRfcSectionBase.java:289)
	at org.apache.catalina.servlets.TestWebdavServletRfcSection_9_11.testRfc_9_11_1(TestWebdavServletRfcSection_9_11.java:190)	
```

**Comment by rmaucher** [comment]
+1 for the third one (the request will not work so it's better to send the specified 400 code immediately), I just fixed it.
For the other two, about depth, I left it as is on purpose. There's no status code mentioned for a bad depth, and there's a default value if absent. IMO pretending it's either 0 if specified or inifinity otherwise is not bad.
Note: There are some items where you must not be strict like the lock timeout just after the depth header in the code.

BTW, if you submit tests, having a WebDAV compliance testsuite is not a goal for Tomcat (it was structured that way with HTTP/2 because HTTP/2 is critical for Tomcat), although we're probably not going to refuse it. The general idea is to have good coverage and cover some complex scenarios. Maybe you can submit code to Litmus and see what happens if something is not covered by it (evidently the three items here are not since Litmus is all ok), since the goal there is to be a WebDAV compliance testsuite.

WebdavServletRfcSectionBase (renamed to WebdavServletBaseTest IMO) could be a good idea to make the existing tests less verbose. Verifying it is really the case would be start, of course.

**Comment by rmaucher** [comment]
Ok, I give up on that one, since it's already done for copyResource. I gave you credit in the commit message.

**Pull request closed without merging**
