### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Review by martin-g — COMMENTED** [review]
The renamed classes and methods might need to keep their old versions as deprecated to be backward compatible.

**Comment by markt-asf** [comment]
There is lots of good stuff here but also changes to some files that we can't (due to ASF policy w.r.t. 3rd party licenses) change. And as Martin pointed out changing anything that might be considered part of the public API needs careful consideration.
I'm currently trying to figure out the best way to handle this

**Comment by markt-asf** [comment]
OK. I have a plan. I have checked out the source branch for the PR locally and am using a visual diff tool to compare this PR with Tomcat. The tool provides tools to easily review the changes in the PR and apply them selectively to Tomcat. I'll apply changes manually. If you can rebase this PR periodically, that will enable this PR to reflect the current TODO list in terms of what needs to be reviewed (and potentially merged). There will be some changes that can't be made in Tomcat. I can direct you to the correct upstream project for those. If you can remove those changes from this PR and submit PRs for the appropriate project(s) that would be very helpful.

**Comment by jbampton** [comment]
Hey @markt-asf thanks for reviewing.  I will help out as much I can, rebase when needed etc and I will do PR's in the appropriate projects as directed.

**Comment by markt-asf** [comment]
Thanks for being so understanding. I'm starting to commit changes as I review them. Here is the frist batch of files we won;t be able to change. This should be the majority of them.

Changes in the following files need to be submitted as PRs against https://github.com/eclipse-ee4j/jakartaee-schemas
- jakartaee_9.xsd
- jakartaee_web_services_2_0.xsd
- jakartaee_web_services_client_2_0.xsd
- jsp_3_0.xsd
- web-app_5_0.xsd
- web-fragment_5_0.xsd
- web-jsptaglibrary_3_0.xsd

Changes in the following files need to be removed from this PR (and I am not sure if there is an upstream project for them)
- javaee_8.xsd
- javaee_web_services_1_2.xsd
- javaee_web_services_1_3.xsd
- javaee_web_services_1_4.xsd
- javaee_web_services_client_1_2.xsd
- javaee_web_services_client_1_3.xsd
- javaee_web_services_client_1_4.xsd
- web-app_3_0.xsd
- web-app_3_1.xsd
- web-app_4_0.xsd
- web-fragment_3_0.xsd
- web-fragment_3_1.xsd
- web-fragment_4_0.xsd

The remaining schemas and DTDs are old enough that they originated at the ASF so we can fix them.

**Comment by martin-g** [comment]
Any Github project member can push to the contributor's branch if it is a
source of a PR.

**Comment by markt-asf** [comment]
The following changes are not correct and need to be reverted:
- org.apache.catalina.manager  - "received" is correct
- org.apache.servlets "external" is correct spelling
- org.apache.catalina.tribes.group.interceptors "weren't" is correct
- package org.apache.catalina.valves "triple" is correct

**Comment by pzygielo** [comment]
> The following changes are not correct and need to be reverted:
>     * org.apache.servlets "external" is correct spelling

What do you mean by that? It seems this PR fixed `enternal` into `external` exactly. :confused:

**Comment by markt-asf** [comment]
You can ignore all of those. I managed to flip the old and new so I was looking at them the wrong way round.

**Comment by markt-asf** [comment]
DBCP and pool need to be fixed in the respective Commons projects. I have commit access there so I've done that and those changes can be removed from this PR.

**Comment by markt-asf** [comment]
There were fewer API changes than expected the changes in the PR have been applied excluding the DTD/schema files identified above. If you could rebase the PR and confirm nothing has been missed that would be great.

**Comment by jbampton** [comment]
Hey @markt-asf I just rebased and we have 20 files changed only in the `.xsd` files. 

Seems to be the same twenty that was in your list.

**Comment by markt-asf** [comment]
Great. Thanks for the confirmation. On that basis, I am going to close the PR. Thanks for all the fixes.

**Pull request closed without merging**
