### PR TITLE
https://bz.apache.org/bugzilla/show_bug.cgi?id=63333

### PR DESCRIPTION
**Pull request by jchobantonov**
JAASRealm needs to override isAvailable method to prevent LockOutRealm to lock the user in case JAAS login modules are unavailable

### CODE REVIEW

**Comment by ChristopherSchultz** [comment]
No explanation?

-1

**Comment by michael-o** [comment]
I agree with @ChristopherSchultz .

**Comment by jchobantonov** [comment]
the explanation of the reason is here 
https://bz.apache.org/bugzilla/show_bug.cgi?id=63333

**Comment by ChristopherSchultz** [comment]
But an explanation should be included with all PRs. What if BZ is deleted? (It shouldn't be, but there's no reason to make people walk all over the internet to find information that could easily be summarized in a single sentence.)

**Comment by ChristopherSchultz** [comment]
Code comments would be helpful, here, too.

**Comment by jchobantonov** [comment]
Code comments are exactly the same as what tomcat source code have for DataSourceRealm, not sure what else do you need as a comment there.

**Comment by isapir** [comment]
I think that it'd be cleaner/more readable if `invocationSuccess` is initialized with `false` value and only set to `true` upon success, or at least after the first block that calls `LoginContext()` succeeds, instead of repeating it in lines 414, 423, 428, 433, and 437.

**Comment by ChristopherSchultz** [comment]
The low-quality of the existing code and/or documentation is not an excuse for maintaining that level of quality.

**Comment by ChristopherSchultz** [comment]
> I think that it'd be cleaner/more readable if `invocationSuccess` is initialized with `false` value and only set to `true` upon success, or at least after the first block that calls `LoginContext()` succeeds, instead of repeating it in lines 414, 423, 428, 433, and 437.

The availability of the JAAS service might go up and down, so you can't just set it once and forget about it, of course. To reduce the number of changed lines and opportunities for mistakes, there could be a local flag for success which is copied to the global flag after each transaction.

**Comment by jchobantonov** [comment]
> I think that it'd be cleaner/more readable if `invocationSuccess` is initialized with `false` value and only set to `true` upon success, or at least after the first block that calls `LoginContext()` succeeds, instead of repeating it in lines 414, 423, 428, 433, and 437.

It is initialized to true as what we have in DataSourceRealm already - not sure why we need to initialize it to false - initialize to true means that it is available and when we detect it is not then we change that to be not available

**Comment by jchobantonov** [comment]
> The low-quality of the existing code and/or documentation is not an excuse for maintaining that level of quality.

Ok, let me know what you think we should put as a comment additionally that is so greatly missed and it is not obvious enough for you or someone else and I will add it

**Comment by isapir** [comment]
> To reduce the number of changed lines and opportunities for mistakes, there could be a local flag for success which is copied to the global flag after each transaction.

But these lines are all in the same transaction, no?

> initialize to true means that it is available and when we detect it is not then we change that to be not available

OK, but why not set `invocationSuccess = true;` at line 405, for example, instead of repeating it in each catch block?  The only difference I see in these blocks is the log message (with the exception of that last block of course, which sets the flag to `false`). https://github.com/apache/tomcat/blob/39f55d8c6f5658a8ea730ebbf8cc1680194c5a48/java/org/apache/catalina/realm/JAASRealm.java#L405

**Comment by jchobantonov** [comment]
> But these lines are all in the same transaction, no?

Yes they are - there is no need to use local variable as well - it is the same - if you forget to set invocationSuccess variable to correct value you could forget to set the local variable as well

> OK, but why not set `invocationSuccess = true;` at line 405, for example, instead of repeating it in each catch block? The only difference I see in these blocks is the log message (with the exception of that last block of course, which sets the flag to `false`).

because if you to have another thread trying to access the LockOutRealm and you put the 'invocationSuccess = true' on line 405 you could just change the failed invocation e.g. invocationSuccess from false to true on line 405 to only put the variable back to false when the next attempt fails again

**Comment by isapir** [comment]
> Ok, let me know what you think we should put as a comment additionally that is so greatly missed and it is not obvious enough for you or someone else and I will add it

> because if you to have another thread trying to access the LockOutRealm and you put the 'invocationSuccess = true' on line 405 you could just change the failed invocation e.g. invocationSuccess from false to true on line 405 to only put the variable back to false when the next attempt fails again

Well then, here's an excellent opportunity for a comment so that someone wouldn't edit it later without taking this into account.

**Comment by jchobantonov** [comment]
@isapir @ChristopherSchultz  I have added more comments hope this helps

**Comment by jchobantonov** [comment]
@markt-asf ^

**Comment by markt-asf** [comment]
Just a note to say this next on my list to look at - hopefully tomorrow.

**Comment by markt-asf** [comment]
I've applied this. I didn't merge the PR directly as I wanted to tweak some of the formatting but the functional aspects remained unchanged. I also added a changelog entry and credited you there.

**Pull request closed without merging**
