### PR TITLE
Update OpenSSLEngine.java  changed 'toArray(new String[size])'  to  'toArray(new String[0])'

### PR DESCRIPTION
**Pull request by DigitalFatCat**
It should use 'toArray(new String[0])' instead of 'toArray(new String[size])'

### CODE REVIEW

**Comment by aooohan** [comment]
It doesn't make sense to do this.

**Comment by markt-asf** [comment]
It usually does make sense. See https://www.baeldung.com/java-collection-toarray-methods
I thought we'd been through the code base and fixed all these previously. A quick search indicates that isn't the case - or we missed quite a few. I have patch locally to address all of the remaining toArray() calls that I just need to review before committing.

**Comment by aooohan** [comment]
> It usually does make sense. See https://www.baeldung.com/java-collection-toarray-methods

Wow, interesting, it turns out that there is a difference in performance between these. I am ashamed of my ignorance.
> I have patch locally to address all of the remaining toArray() calls that I just need to review before committing.

Ok

**Comment by aooohan** [comment]
@DigitalFatCat  Thanks for the PR.  : )

**Comment by ChristopherSchultz** [comment]
If we _really_ want to improve performance, we should be using static zero-sized arrays instead of instantiating them each time. A zero-item array is immutable, and thus infinitely sharable everywhere.

**Comment by ChristopherSchultz** [comment]
> > It usually does make sense. See https://www.baeldung.com/java-collection-toarray-methods
> 
> Wow, interesting, it turns out that there is a difference in performance between these. I am ashamed of my ignorance.

You should not feel bad at all. It makes absolutely zero sense that this would be faster than anything else, and yet it is measurably so.

**Pull request closed without merging**
