### PR TITLE
Upgrade Readability by removing brackets

### PR DESCRIPTION
**Pull request by iamjooon2**
Hi there!

i deleted needless brackets for consistency with the other code.

Thx :D

### CODE REVIEW

**Comment by markt-asf** [comment]
We have started to get a lot of PRs removing single instances of unnecessary parentheses. While we are generally in favour of this sort of clean-up, one PR per instance is not scaleable and will generate a LOT of noise on the mailing list.

Automated tools aren't the answer as there are a reasonable proportion of these unnecessary parentheses we will want to keep as they aid readability of the code.

If you expanded this PR to cover all the classes in the package then that is probably at a scale that would be manageable.

**Comment by iamjooon2** [comment]
@markt-asf I just saw [!This PR](https://github.com/apache/tomcat/pull/650) and removed some brackets too

Regret for comment 'Automated tools'😕

**Comment by iamjooon2** [comment]
HI @markt-asf 

I read codes in apache/coyote

I found

**Comment by iamjooon2** [comment]
Hello from Korea @markt-asf
I unified all of conventions in package apache/coyote

1. unify conditional convention
e.g
```java
// from
if (type == Constants.JK_AJP13_CPING_REQUEST) {
    if (protocol.isPaused()) {
        recycle();
        break;
    }
    ..
}
// to

if (type == Constants.JK_AJP13_CPING_REQUEST && protocol.isPaused()) {
  recycle();
  break;
}

```
removed unnecessary depth.

2. 
unify brackets conventions in apache/coytote

And...
When I first wrote this PR, I wrote it with a pure heart that I also want to be helpful. I had no other intention 
If there's anything lacking on my PR, I'd like you to leave it
Have a good day :)

**Review by markt-asf — CHANGES_REQUESTED** [review]
This doesn't compile. There are unacceptable (I assume unintended)  behavioural changes.

**Comment by iamjooon2** [comment]
My mistake!
I rollbacked some codes.

I really appreciate for your comment!

**Comment by iamjooon2** [comment]
I rollbacked some codes.
I really appreciate for your comments. 

Have a good Day

**Review by markt-asf — CHANGES_REQUESTED** [review]
My previous review comments have not been addressed.

The merge of `if` statements has not been performed correctly in `AjpProcessor` and, further, the merge has changed the functionality which is not acceptable in this case.

**Pull request merged**
