### PR TITLE
Display the CATALINA_OPTS when starting Tomcat

### PR DESCRIPTION
**Pull request by rpluem**

### CODE REVIEW

**Comment by markt-asf** [comment]
Fair enough. I'm a little concerned about the slippery slope argument leading to all config being displayed but this is a regularly enough used option that I think the case for including it is reasonable.

**Comment by rpluem** [comment]
Thanks. Is there anything I need to do to get this backported for 9.0.x, e.g. a separate PR against the 9.0.x branch?

**Comment by markt-asf** [comment]
Nope. I back-ported it all the way to 7.0.x shortly after I merged the PR.

**Comment by rpluem** [comment]
Great :-). Thanks.

**Pull request merged**
