### PR TITLE
Use StringBuilder instead of StringBuffer

### PR DESCRIPTION
**Pull request by martin-g**
There is no need of synchronization when it is a method local variable.

Append character instead of String when possible

### CODE REVIEW

**Comment by rmaucher** [comment]
The "Append character instead of String when possible" seems wrong to me, and you're editing generated code there.

**Comment by martin-g** [comment]
@rmaucher Could you please comment on the changed lines ?
I am not sure which code is generated and which `append(char)` might be wrong.
Thanks!

**Comment by pzygielo** [comment]
> and which `append(char)` might be wrong.

I suppose, there is change in produced result
```
(1)              retval.append("\\t");
(2)              retval.append('\t');
```
as in first case "\t" (i.e. two-char string: `\` followed by `t`) is appended, and in second case - tab character ('\t') is.
Unfortunately I can't tell if there is test to validate what is expected as all smoke test jobs pass.

**Comment by martin-g** [comment]
Thanks, @pzygielo !

Also these seem to be the generated classes!

**Comment by martin-g** [comment]
I've reverted the changes to the generated classes.

What about the DBCP2 classes ? Maybe they should be changed upstream and then copied over here ?

**Comment by markt-asf** [comment]
Yes, DBCP2 changes need to be made upstream.

**Comment by martin-g** [comment]
OK. I've reverted the DBCP classes!
And made some more changes from `.append(String)` to `.append(char)`

**Comment by rmaucher** [comment]
Looks good to me now. The change for rewrite is likely the most significant, the rest is probably not doing anything though.

**Pull request merged**
