### PR TITLE
Polish. NioEndpoint

### PR DESCRIPTION
**Pull request by aooohan**
As I was learning tomcat, I discovered some logic that could be extracted into separate methods. Hope my pr is useful.

### CODE REVIEW

**Comment by rmaucher** [comment]
Ok why not. interestOpsEquals is a bad name though, maybe interestOpsHas or something like it ?

**Comment by aooohan** [comment]
> Ok why not. interestOpsEquals is a bad name though, maybe interestOpsHas or something like it ?
Thanks for the comment，interestOpsHas is better name than interestOpsEquals and i will update it.

**Comment by aooohan** [comment]
> Ok why not. interestOpsEquals is a bad name though, maybe interestOpsHas or something like it ?

Thanks for your comment, interestOpsHas a better name than interestOpsEquals and I will update it.

**Comment by markt-asf** [comment]
Applied manually go I could merge the polish commits and make a couple of minor changes.

**Pull request closed without merging**
