### PR TITLE
Fix: evict cached MBean when bean descriptor content changed to ensure ManagedBean#getMBeanInfo result is correct.

### PR DESCRIPTION
**Pull request by Chenjp**
1. ensure evict cache for each modification like returnType, name, desc, addAttribute etc. 
2. code refactoring.
3. testcase added.

### CODE REVIEW

**Comment by markt-asf** [comment]
Why would MBean info change at runtime? The MBeans pretty much all represent Tomcat internals and they don't change structure at runtime. I'm not seeing the use case for this.

**Comment by rmaucher** [comment]
In theory this is an upstream issue (commons-modeler), however it is no longer maintained.

**Comment by Chenjp** [comment]
> In theory this is an upstream issue (commons-modeler), however it is no longer maintained.

got it.

**Comment by markt-asf** [comment]
Unless a valid use case is provided for this change, this PR will be closed without being applied.

**Comment by Chenjp** [comment]
No valid use case.

**Pull request closed without merging**
