### PR TITLE
Bug fix: If-None-Match: 304 response should return a real resource ETag

### PR DESCRIPTION
**Pull request by stokito**
In the scope of bef507e1b7ac2eb0ff012d0d40035e218a5839cc was added a bug:

```
curl -vv http://localhost:8080/tomcat.png -H 'If-None-Match: W/"5103-1595887733334"'
> GET /tomcat.png HTTP/1.1
> Accept: */*
> If-None-Match: W/"5103-1595887733334"
> 
< HTTP/1.1 304 
< ETag: "5103-1595887733334"
< Date: Tue, 11 Aug 2020 20:27:30 GMT
```

The real ETag is weak `W/"5103-1595887733334"` but returned in response was strict `"5103-1595887733334"`.
This happens because on line 2261 value of the `eTag` variable is changed:

      if (eTag.startsWith("W/")) {
            eTag = eTag.substring(2);
      }

and then it goes to response.
The PR fixes this. Also I tried to make the both `checkIfNoneMatch()` and `checkIfMatch()` functions looking similar.
Now we can extract their common logic to a separate function.

### CODE REVIEW

**Comment by michael-o** [comment]
The entire ETag handling requires an overhaul.

**Comment by markt-asf** [comment]
In reviewing this PR I've noticed another issue. The ETag obtained from the resource is unconditionally made strong before the comparison but that conversion should depend on `useWeakComparisonWithIfMatch`.
I'm not convinced of the case for aligning the two methods and fixing this new issue looks like it will weaken that case.
The test case change looks good. I'll add that, add a test for the new issue and then look at a fix for both issues.

**Comment by stokito** [comment]
yes, you are right and I wanted to discuss it latter. The PR fixes only one specific problem + small refactoring.
The problem that I see is that the new `useWeakComparisonWithIfMatch` flag is not complaint with RFC because it always should be strict.

    An origin server MUST use the strong comparison function when comparing entity-tags for If-Match (Section 2.3.2), since the client intends this precondition to prevent the method from being applied if there have been any changes to the representation data.

In fact as far I understood the weak comparison for `If-Match` was implemented by mistake in scope of b26ad77f659de34d49dda5a248566a38383cec0e. And this happened recently. That means that in fact here we making the bug as a feature. This may have sense if there is a lot of users who used this behavior but in fact we definitely haven't any of them.

Did I miss something? Can we simplify logic and and inline useWeakComparisonWithIfMatch as a false?

**Comment by stokito** [comment]
I added a commit that extracts common matching logic

**Comment by markt-asf** [comment]
Let me go an look at `b26ad77` in more detail. If the switch to weak comparison was introduced there then the case for fixing that and dropping `useWeakComparisonWithIfMatch` entirely is much stronger.

**Comment by markt-asf** [comment]
After looking at b26ad77 I have reverted the addition of `useWeakComparisonWithIfMatch` and switched If-Match to strong comparison. I've also fixed the regression you identified. With these changes the If-Match and If-None-Match code has diverged a little further. I thin kthe case for refactoring is rather borderline at the moment but take a look at the new code and see what you think.

**Comment by stokito** [comment]
I reviewed and it looks fine and simpler. I just want to note here for history that according RFC 7232 sec 2.3.2 if resource's real etag is weak than strong comparison always failed:

ETag 1 | ETag 2 | Strong Comparison | Weak Comparison
-- | -- | -- | --
W/"1" | W/"1" | no match | match
W/"1" | W/"2" | no match | no match
W/"1" | "1" | no match | match
"1" | "1" | match | match

That's why in my version I added the note:

            // BZ 64265: By default Tomcat generates weak etag for resource.
            // But If-Match uses strong matching that expects a strong resource etag.
            // So we strip any leading "W/" and then compare using equals
            String resourceEtag = weakEtagToStrong(eTag);

I.e. that code is a workaround for fact that Tomcat generates weak ETag for static resource while should generate strong (that was discussed in #324). Now when client will send the received weak etag it will always get 412. And this is correct according spec but may be unexpected for a client. But I'm pretty sure that nobody uses the `If-Match` anyway: a browser never sends it.
I think that we should keep this version and instead in some feature releases switch Tomcat to generate strong etags by default.
But this is another story.

**Pull request closed without merging**
