### PR TITLE
now json is fashion

### PR DESCRIPTION
**Pull request by ahu0605**
The class should support data json

### CODE REVIEW

**Comment by markt-asf** [comment]
This pull request is declined. Even ignoring the poor quality of this pull request, supporting JSON formatted data is an application concern, not a container concern.

**Comment by ahu0605** [comment]
but when i push content type - json，there is some bug , 4 ex :data is json "{\"id\":\"asd\"}",the value  will be a Map key, request.getPamaterMap () the key is {"id":"asd"}, value is null ,is not logic

**Comment by martin-g** [comment]
When you POST JSON data you should use http://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getReader() to consume the body and parse it as you find appropriate.

**Comment by hazendaz** [comment]
We run json using Jackson with jersey in tomcat.  No issues.  This code doesn't do anything.  So unclear how it solves anything.  All you did was add an empty if statement.

--- Original Message ---

**Comment by martin-g** [comment]
I'm pretty sure Jersey does something.

**Comment by hazendaz** [comment]
Sure...what I meant here is that this patch does nothing from tomcat perspective.  It's just an empty if statement.  It does nothing at all.

--- Original Message ---

**Comment by ahu0605** [comment]
I am very sad this bug is not be modifed, PHP had surpported  content -type :JSON ,but java ...

**Comment by ebourg** [comment]
As I understand this pull request is more a request for enhancement than an actual code contribution. I guess you suggest that Tomcat implements the [W3C HTML JSON form submission](http://www.w3.org/TR/html-json-forms/) draft, correct?

**Comment by ahu0605** [comment]
yes,from Perspective of development. it is benifit  java ,it is benifit  Tomcat ,our company has choice resin,if the problem keep alive, i maybe choice  PHP or Python

**Pull request closed without merging**
