### PR TITLE
Clear up confusion about mbeans-descriptors.xml in docs; fix a type i…

### PR DESCRIPTION
**Pull request by rhusar**
…n core descriptor

Lets make sure its everywhere called "mbeans-descriptors" otherwise one missing "s" can cost developers quite a while debugging what is wrong.

### CODE REVIEW

**Comment by violetagg** [comment]
Hi,

I have one comment about renaming the page.
If there are bookmarks to that page with this change we will break these bookmarks.

Otherwise the change is OK.

Wdyt?

Regards,
Violeta

**Comment by violetagg** [comment]
Hello,

Typos are fixed with r1755675.

Regards,
Violeta

**Comment by markt-asf** [comment]
Rename the page. If someone complains, we can look at adding a redirect although we'll need to handle both Tomcat (for releases) and httpd (for the website). I'd prefer to have a single solution for both but I don;t see one at this point.

**Comment by rhusar** [comment]
My thinking is that first, we need to stop perpetuating the wrong name "mbeans-descriptor" which is the name of the page, and more importantly, the page gives such a bad advice that it  deserves a rename since nobody could have been using it.

**Comment by violetagg** [comment]
Hi,

Your patch was applied with r1755717.

Regards,
Violeta

**Comment by rhusar** [comment]
👍

**Pull request closed without merging**
